name: zpy
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libgcc_mutex=0.1=free
  - _openmp_mutex=4.5=2_gnu
  - brotli-python=1.0.9=py39h5da7b33_9
  - ca-certificates=2025.2.25=haa95532_0
  - cuda-cudart=12.8.90=he0c23c2_1
  - cuda-cudart_win-64=12.8.90=he0c23c2_1
  - cuda-cupti=12.8.90=he0c23c2_1
  - cuda-nvrtc=12.8.93=he0c23c2_1
  - cuda-version=12.8=h5d125a7_3
  - cudnn=9.8.0.87=h1361d0a_1
  - freetype=2.13.3=h57928b3_1
  - giflib=5.2.2=h7edc060_0
  - git=2.49.0=h57928b3_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py39h827c3e9_0
  - importlib_resources=6.4.0=py39haa95532_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - jpeg=9e=h827c3e9_3
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.1=cxx17_h4eb7d71_0
  - libblas=3.9.0=31_h641d27c_mkl
  - libcblas=3.9.0=31_h5e41251_mkl
  - libcublas=12.8.4.1=he0c23c2_1
  - libcudss=0.5.0.16=hffc9a7f_1
  - libcufft=11.3.3.83=he0c23c2_1
  - libcurand=10.3.9.90=he0c23c2_1
  - libcusolver=11.7.3.90=he0c23c2_1
  - libcusparse=12.5.8.93=he0c23c2_1
  - libdeflate=1.22=h5bf469e_0
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgomp=14.2.0=h1383e82_2
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - liblapack=3.9.0=31_h1aa476e_mkl
  - libmagma=2.9.0=he50f1ff_0
  - libnvjitlink=12.8.93=he0c23c2_1
  - libpng=1.6.47=had7236b_0
  - libprotobuf=5.29.3=he9d8c4a_1
  - libtiff=4.5.0=h8a3f274_0
  - libtorch=2.6.0=cuda126_mkl_h09c782d_304
  - libuv=1.50.0=h2466b09_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxml2=2.13.7=he286e8c_0
  - libzlib=1.3.1=h2466b09_2
  - matplotlib-base=3.9.2=py39he19b0ae_1
  - mkl=2024.2.2=h66d3029_15
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py39haa95532_0
  - networkx=3.2.1=py39haa95532_0
  - openssl=3.4.1=ha4e3fda_0
  - optree=0.14.1=py39h214f63a_0
  - packaging=24.2=py39haa95532_0
  - pip=25.0=py39haa95532_0
  - pybind11=2.13.6=py39h214f63a_1
  - pybind11-global=2.13.6=py39h214f63a_1
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python_abi=3.9=2_cp39
  - pytorch=2.6.0=cuda126_mkl_py39_h442358c_304
  - scipy=1.13.1=py39h1a10956_0
  - setuptools=75.8.0=py39haa95532_0
  - six=1.17.0=py39haa95532_0
  - sleef=3.8=h7e360cc_0
  - sqlite=3.45.3=h2bbff1b_0
  - sympy=1.13.3=py39haa95532_1
  - tbb=2021.13.0=h62715c5_1
  - tk=8.6.12=h2bbff1b_0
  - torchcam=0.4.0=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py39haa95532_0
  - typing_extensions=4.12.2=py39haa95532_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py39h827c3e9_1
  - vc=14.42=haa95532_4
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wheel=0.45.1=py39haa95532_0
  - xz=5.6.4=h4754444_1
  - zipp=3.21.0=py39haa95532_0
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - advertorch==0.2.3
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.15
      - aiosignal==1.3.2
      - arrow==1.3.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - boto3==1.37.24
      - botocore==1.37.24
      - bravado==11.1.0
      - bravado-core==6.1.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - dill==0.3.9
      - easypyxl==1.0.1
      - et-xmlfile==2.0.0
      - filelock==3.16.1
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.1
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - isoduration==20.11.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.14.2
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - monotonic==1.6
      - msgpack==1.1.0
      - multidict==6.3.0
      - narwhals==1.33.0
      - neptune==1.13.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pillow==11.2.1
      - plotly==6.0.1
      - portalocker==3.1.1
      - propcache==0.3.1
      - psutil==7.0.0
      - pyjwt==2.10.1
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pywin32==310
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.24.0
      - s3transfer==0.11.4
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - simplejson==3.20.1
      - smmap==5.0.2
      - swagger-spec-validator==3.0.4
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==1.0.15
      - torch==2.8.0.dev20250330+cu128
      - torchaudio==2.6.0.dev20250331+cu128
      - torchmetrics==1.7.0
      - torchvision==0.22.0.dev20250331+cu128
      - tqdm==4.67.1
      - ttach==0.0.3
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==1.26.20
      - webcolors==24.11.1
      - websocket-client==1.8.0
      - yarl==1.18.3
prefix: C:\ProgramData\anaconda3\envs\zpy
